### ISSUE TITLE
Start Action: pre-select last selected "Account" would be handy

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-tekton#384]
**Steps:**
1. ASSERT: have a task
2. EXEC: select task and pick "Start" in the context menu
3. ASSERT: Wizard to select the "Global Service Account" shows up. 
![image](https://user-images.githubusercontent.com/25126/111185778-a2fb8e80-85b2-11eb-82e0-2ffb1b618b51.png)
4. EXEC: Look at "Global Service Account" combo

**Result:**
If "Global Service Account" was pre-selecting the last account that I used (prior "Start" action), i could simply hit "Start". This would be very handy.

**Comment by lstocchi** [comment]
There are two ways you can bypass this. First, there is a setting to avoid opening the start wizard if there are no inputs to insert. Second there is the mirror start action which copies the input values of an old *run, just select it and it starts the task with the same input values. Is this enough? Pre-selecting the last selected account may leads to errors i think

**Comment by adietish** [comment]
> there is a setting to avoid opening the start wizard if there are no inputs to insert. 

Can you please explain what's "not inputs"?

**Comment by adietish** [comment]
> Pre-selecting the last selected account may lead to errors i think

Can lead to errors if it wasn't possible to see what's pre-selected. I was thinking of opening the wizard - as it already does currently - but preselecting what has been used the last time that the wizard was opened. I think that this is a very common pattern that users are used to and as such shouldn't lead to problems while offering an additional step of ease.

**Comment by lstocchi** [comment]
> Can you please explain what's "no inputs"?

No params/workspaces/input and output resources to be set

**Comment by lstocchi** [comment]
After thinking at it i'm going to close this issue because i don't see how it can be improved in a way that fully convince me. 

The property is optional and it is clearly stated next the name. 
I cannot pre-select something and being certain that that is the right choice. It would be just a guess, so i prefer to "guess" the user won't need any service account to run the task/pipeline.

Real pipelines have many tasks and inputs and it's likely they need a specific serviceAccount with specific rights to run. What are the chances we're going to guess that? I prefer to leave it to the user, even because by guessing the wrong service account to be used we could create some security issue to careless ppl.

![image](https://user-images.githubusercontent.com/49404737/128357089-ffecb6c8-e041-4f96-80bd-3770fd4216e5.png)
